package com.example.moviesgo.model

data class Movies(
    val Title: String,
    val year: String,
    val Rated: String,
    val Released: String,
    val RunTime: String,
    val genre: String,
    val director: String,
    val writer: String,
    val actors: String,
    val plot: String,
    val lang: String,
    val country: String,
    val awards: String,
    val poster: String,
    var imdbID: String
)

fun getMovies(): List<Movies> {

    return listOf(

        Movies(
            Title = "The Shawshank Redemption",
            year = "1994",
            Rated = "R",
            Released = "14 Oct 1994",
            RunTime = "142 min",
            genre = "Drama",
            director = "Frank Darabont",
            writer = "Stephen King, Frank Darabont",
            actors = "Tim Robbins, Morgan Freeman, Bob Gunton",
            plot = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
            lang = "English",
            country = "United States",
            awards = "Nominated for 7 Oscars. 21 wins & 43 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
            imdbID = "tt0111161"
        ),
        Movies(
            Title = "The Godfather",
            year = "1972",
            Rated = "R",
            Released = "24 Mar 1972",
            RunTime = "175 min",
            genre = "Crime, Drama",
            director = "Francis Ford Coppola",
            writer = "Mario Puzo, Francis Ford Coppola",
            actors = "Marlon Brando, Al Pacino, James Caan",
            plot = "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.",
            lang = "English, Italian, Latin",
            country = "United States",
            awards = "Won 3 Oscars. 31 wins & 30 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            imdbID = "tt0068646"
        ),
        Movies(
            Title = "The Dark Knight",
            year = "2008",
            Rated = "PG-13",
            Released = "18 Jul 2008",
            RunTime = "152 min",
            genre = "Action, Crime, Drama",
            director = "Christopher Nolan",
            writer = "Jonathan Nolan, Christopher Nolan, David S. Goyer",
            actors = "Christian Bale, Heath Ledger, Aaron Eckhart",
            plot = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
            lang = "English, Mandarin",
            country = "United States, United Kingdom",
            awards = "Won 2 Oscars. 159 wins & 163 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
            imdbID = "tt0468569"
        ),
        Movies(
            Title = "The Godfather: Part II",
            year = "1974",
            Rated = "R",
            Released = "18 Dec 1974",
            RunTime = "202 min",
            genre = "Crime, Drama",
            director = "Francis Ford Coppola",
            writer = "Francis Ford Coppola, Mario Puzo",
            actors = "Al Pacino, Robert De Niro, Robert Duvall",
            plot = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
            lang = "English, Italian, Spanish, Latin, Sicilian",
            country = "United States",
            awards = "Won 6 Oscars. 17 wins & 20 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            imdbID = "tt0071562"
        ),
        Movies(
            Title = "12 Angry Men",
            year = "1957",
            Rated = "Approved",
            Released = "10 Apr 1957",
            RunTime = "96 min",
            genre = "Crime, Drama",
            director = "Sidney Lumet",
            writer = "Reginald Rose",
            actors = "Henry Fonda, Lee J. Cobb, Martin Balsam",
            plot = "The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.",
            lang = "English",
            country = "United States",
            awards = "Nominated for 3 Oscars. 17 wins & 13 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg",
            imdbID = "tt0050083"
        ),
        Movies(
            Title = "Schindler's List",
            year = "1993",
            Rated = "R",
            Released = "04 Feb 1994",
            RunTime = "195 min",
            genre = "Biography, Drama, History",
            director = "Steven Spielberg",
            writer = "Thomas Keneally, Steven Zaillian",
            actors = "Liam Neeson, Ralph Fiennes, Ben Kingsley",
            plot = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
            lang = "English, Hebrew, German, Polish, Latin",
            country = "United States",
            awards = "Won 7 Oscars. 91 wins & 49 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
            imdbID = "tt0108052"
        ),
        Movies(
            Title = "The Lord of the Rings: The Return of the King",
            year = "2003",
            Rated = "PG-13",
            Released = "17 Dec 2003",
            RunTime = "201 min",
            genre = "Action, Adventure, Drama",
            director = "Peter Jackson",
            writer = "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
            actors = "Elijah Wood, Viggo Mortensen, Ian McKellen",
            plot = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
            lang = "English, Quenya, Old English, Sindarin",
            country = "New Zealand, United States",
            awards = "Won 11 Oscars. 209 wins & 124 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            imdbID = "tt0167260"
        ),
        Movies(
            Title = "Pulp Fiction",
            year = "1994",
            Rated = "R",
            Released = "14 Oct 1994",
            RunTime = "154 min",
            genre = "Crime, Drama",
            director = "Quentin Tarantino",
            writer = "Quentin Tarantino, Roger Avary",
            actors = "John Travolta, Uma Thurman, Samuel L. Jackson",
            plot = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
            lang = "English, Spanish, French",
            country = "United States",
            awards = "Won 1 Oscar. 70 wins & 75 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
            imdbID = "tt0110912"
        ),
        Movies(
            Title = "The Lord of the Rings: The Fellowship of the Ring",
            year = "2001",
            Rated = "PG-13",
            Released = "19 Dec 2001",
            RunTime = "178 min",
            genre = "Action, Adventure, Drama",
            director = "Peter Jackson",
            writer = "J.R.R. Tolkien, Fran Walsh, Philippa Boyens",
            actors = "Elijah Wood, Ian McKellen, Orlando Bloom",
            plot = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
            lang = "English, Sindarin",
            country = "New Zealand, United States",
            awards = "Won 4 Oscars. 121 wins & 126 nominations total",
            poster = "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
            imdbID = "tt0120737"
        ),
        Movies(
            Title = "The Good, the Bad and the Ugly",
            year = "1966",
            Rated = "R",
            Released = "29 Dec 1967",
            RunTime = "178 min",
            genre = "Adventure, Western",
            director = "Sergio Leone",
            writer = "Luciano Vincenzoni, Sergio Leone, Agenore Incrocci",
            actors = "Clint Eastwood, Eli Wallach, Lee Van Cleef",
            plot = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
            lang = "Italian",
            country = "Italy, Spain, West Germany",
            awards = "3 wins & 6 nominations",
            poster = "https://m.media-amazon.com/images/M/MV5BNjJlYmNkZGItM2NhYy00MjlmLTk5NmQtNjg1NmM2ODU4OTMwXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
            imdbID = "tt0060196"
        )
    )
}